export const ROUTES = {
  HOME: "/",
  SHOP: "/shop",
  PRODUCT: "/product/:slug",
  CART: "/cart",
  CHECKOUT: "/checkout",
  ORDER_CONFIRMATION: "/order-confirmation/:orderNumber",
  ABOUT: "/about",
  CONTACT: "/contact",
  ADMIN: {
    ROOT: "/admin",
    LOGIN: "login",
    LOGIN_PATH: "/admin/login",
    PRODUCTS: "products",
    PRODUCT_NEW: "products/new",
    PRODUCT_EDIT: "products/:id/edit",
    ORDERS: "orders",
    CUSTOMERS: "customers",
    COUPONS: "coupons",
    SETTINGS: "settings",
  },
} as const;
