export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  VERIFY_OTP: "/verify-otp",
  SHOP: "/shop",
  PRODUCT: "/product/:slug",
  CART: "/cart",
  CHECKOUT: "/checkout",
  ORDER_CONFIRMATION: "/order-confirmation/:orderNumber",
  ORDER_LOOKUP: "/order-lookup",
  ABOUT: "/about",
  CONTACT: "/contact",
  ACCOUNT: {
    ROOT: "/account",
    PROFILE: "profile",
    PROFILE_PATH: "/account/profile",
    ORDERS: "orders",
    ORDERS_PATH: "/account/orders",
    ORDER_DETAILS: "orders/:orderNumber",
    ADDRESSES: "addresses",
    ADDRESSES_PATH: "/account/addresses",
    WISHLIST: "wishlist",
    WISHLIST_PATH: "/account/wishlist",
  },
  ADMIN: {
    ROOT: "/admin",
    LOGIN: "login",
    LOGIN_PATH: "/admin/login",
    PRODUCTS: "products",
    PRODUCT_NEW: "products/new",
    PRODUCT_EDIT: "products/:id/edit",
    ORDERS: "orders",
    WAREHOUSES: "warehouses",
    CUSTOMERS: "customers",
    COUPONS: "coupons",
    SETTINGS: "settings",
  },
} as const;
